POST http://localhost:3000/auth/refresh-tokens
Content-Type: application/json
Authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjksImVtYWlsIjoibWFya0Bkb2UuY29tIiwiaWF0IjoxNzI0Njc1MzgyLCJleHAiOjE3MjQ2Nzg5ODIsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.3njw95c-tvY5hJYbPooa6FC_K9i0WjzzWvp9yEg1B3A
{
  "refreshToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjksImlhdCI6MTcyNDY3NTM4MiwiZXhwIjoxNzI0NzYxNzgyLCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.ExtLRHNtp1HFs2OprBtku8QzozT1eQ0hWdgu6vJpDdo"
}