POST http://localhost:3000/auth/refresh-tokens
Content-Type: application/json
Authorization : Bearer "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjksImVtYWlsIjoibWFya0Bkb2UuY29tIiwiaWF0IjoxNzI1MTM1NTE4LCJleHAiOjE3MjUxMzkxMTgsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.F2HRs7WCDALovD2WZ_kxhcPgP88eRAOdSVu0KqQy_88"
